# Generated by Django 4.2.5 on 2024-08-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_outlets', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_in', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
    ]
