# Generated by Django 4.2.5 on 2024-11-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_remove_outlet_account_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='name',
            new_name='outlet_name',
        ),
    ]
