# Generated by Django 4.2.5 on 2024-11-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_rename_name_outlet_outlet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, help_text='Enter GST percentage.', max_digits=5)),
                ('is_gst_inclusive', models.BooleanField(default=False, help_text='Indicates if the price is GST inclusive.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='v1.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant name, e.g., 'Large', 'Red'.", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_gst_inclusive', models.BooleanField(default=False, help_text='Indicates if the price is GST inclusive.')),
                ('extra_description', models.JSONField(blank=True, default=list, help_text="List of additional attributes such as 'extra spicy', 'sugar free', etc.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='v1.product')),
            ],
        ),
    ]
