# Generated by Django 4.2.5 on 2024-11-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='v1.outlet')),
            ],
        ),
    ]
