# Generated by Django 4.2.5 on 2024-11-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_order_updated_at_stockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='v1.outlet'),
            preserve_default=False,
        ),
    ]
