# Generated by Django 4.2.5 on 2024-12-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_alter_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrequest',
            name='requested_quantity',
        ),
    ]
