# Generated by Django 4.2.5 on 2024-09-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
