# Generated by Django 4.2.5 on 2024-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_orderitem_gst_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cod', 'Cash on Delivery')], max_length=10, null=True),
        ),
    ]
