# Generated by Django 4.2.5 on 2024-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_order_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash Payment')], max_length=10, null=True),
        ),
    ]
