# Generated by Django 4.2.5 on 2024-11-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_product_category'),
        ('qr', '0007_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='v1.outlet'),
            preserve_default=False,
        ),
    ]
