# Generated by Django 4.2.5 on 2024-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_order_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
